### ISSUE TITLE
Feature: Supporting QueryTimeout

### ISSUE THREAD

**Issue by dzuvic** [w11k/lsql#13]
Hi,

would it be possible to support ps.setQueryTimeout()?

thank you in advance.

**Comment by romanroe** [comment]
@dzuvic Now supported:

https://github.com/w11k/lsql/blob/ac552c9cdb238c6fcb4316028c3de7d592014681/lsql-core/src/main/java/com/w11k/lsql/query/AbstractQuery.java#L86
