### ISSUE TITLE
CLI name inconsistencies 

### ISSUE THREAD

**Issue by pburgmer** [w11k/lsql#33]
* For a column 'VALIDFROM' (two words, but not separated) the CLI generates an interface ValidFromInteger which is stored in a file called ValidfromIngeger.
* For a column 'VALIDTO' it is the other way around: an interface ValidtoInteger stored in a file called ValidToIngeger
* In the result-row-class for 'VALIDFROM' ValidFromInteger is used, for 'VALIDTO' it is ValidToInteger. This is consistent but ValidToInteger does not exist (see bullet 2).

**Comment by romanroe** [comment]
fixed
