### ISSUE TITLE
Jrebel Integration

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/lsql#5]
Is it possible, to reload SQL Files by Jrebel?

**Comment by romanroe** [comment]
Unfortunately, this is not possible right now. For performance reasons, LSql parses an SQL file only once. Replacing the SQL file resource in the classloader would not change the parsed result.

However, I could introduce a "development mode" flag that causes LSql to re-parse the SQL file on every request but I fear the performance penalty for this. How important/urgent is this feature?

**Comment by jblankenhorn** [comment]
This could improve development time quite a bit, but priorite is intermediate i would say
