### ISSUE TITLE
Row.getInt should return Object Integer not primitive Type

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/lsql#7]
Currently it returns an int.
Other methods like getFloat do return an Object Type

**Comment by romanroe** [comment]
@jblankenhorn Which version are you using? getInt does return Integer.

**Comment by jblankenhorn** [comment]
@romanroe 0.6.23

**Comment by jblankenhorn** [comment]
Will (or is) this implemented?

**Comment by romanroe** [comment]
@jblankenhorn This is implemented:

https://github.com/w11k/lsql/blob/master/lsql-core/src/main/java/com/w11k/lsql/Row.java#L130
